#!/usr/bin/env bash
# Debugging nginx installation to listen to port 80 and stop nginx
ls -sfn /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
rm /run/nginx.pid
